In [74]:
import pandas as pd

In [75]:
df=pd.read_csv("/Churn_Modelling.csv")

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [77]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [78]:
df.drop(['Surname','RowNumber'],axis=1,inplace=True)

In [79]:
df.columns

Index(['CustomerId', 'CreditScore', 'Geography', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='object')

In [80]:
df.describe()

,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [81]:
df.isnull().sum()

CustomerId         0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [82]:
df.duplicated().sum()

np.int64(0)

In [83]:
from sklearn.preprocessing import LabelEncoder

In [84]:
from sklearn.model_selection import train_test_split

In [85]:
le = LabelEncoder()

for col in df.select_dtypes(include='object'):
    df[col] = le.fit_transform(df[col])

X = df.drop('Exited', axis=1)

y = df['Exited']

In [86]:
df.head()

,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,15647311,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,15619304,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,15701354,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,15737888,850,2,0,43,2,125510.82,1,1,1,79084.10,0

In [87]:
df['BalanceSalaryRatio'] = df['Balance'] / (df['EstimatedSalary'] + 1)

In [88]:
df['AgeActive'] = df['Age'] * df['IsActiveMember']

In [89]:
df.head()

,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,BalanceSalaryRatio,AgeActive
0,15634602,619,0,0,42,2,0.00,1,1,1,101348.88,1,0.000000,42
1,15647311,608,2,0,41,1,83807.86,1,0,1,112542.58,0,0.744670,41
2,15619304,502,0,0,42,8,159660.80,3,1,0,113931.57,1,1.401362,0
3,15701354,699,0,0,39,1,0.00,2,0,0,93826.63,0,0.000000,0
4,15737888,850,2,0,43,2,125510.82,1,1,1,79084.10,0,1.587035,43

In [90]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [91]:

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

In [92]:
lr = LogisticRegression(max_iter=10000)
lr.fit(X_train, y_train)
pred_lr = lr.predict(X_test)
print(accuracy_score(y_test, pred_lr))

0.7895

In [93]:
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.81      0.97      0.88      1607
           1       0.33      0.07      0.11       393

    accuracy                           0.79      2000
   macro avg       0.57      0.52      0.50      2000
weighted avg       0.71      0.79      0.73      2000

In [94]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
pred_dt = dt.predict(X_test)
print(accuracy_score(y_test, pred_dt))

0.7825

In [95]:
print(classification_report(y_test, pred_dt))

              precision    recall  f1-score   support

           0       0.88      0.85      0.86      1607
           1       0.45      0.52      0.49       393

    accuracy                           0.78      2000
   macro avg       0.67      0.68      0.67      2000
weighted avg       0.80      0.78      0.79      2000

In [96]:
rf = RandomForestClassifier(n_estimators=100,random_state=42,max_depth=10)
rf.fit(X_train, y_train)
pred_rf = rf.predict(X_test)
print(accuracy_score(y_test, pred_rf))

0.8645

In [97]:
print(classification_report(y_test, pred_rf))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1607
           1       0.79      0.43      0.55       393

    accuracy                           0.86      2000
   macro avg       0.83      0.70      0.74      2000
weighted avg       0.86      0.86      0.85      2000

In [98]:
rf = RandomForestClassifier(n_estimators=100,random_state=42,max_depth=15)
rf.fit(X_train, y_train)
pred_rf = rf.predict(X_test)
print(accuracy_score(y_test, pred_rf))

0.868

In [99]:
print(classification_report(y_test, pred_rf))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92      1607
           1       0.78      0.46      0.58       393

    accuracy                           0.87      2000
   macro avg       0.83      0.71      0.75      2000
weighted avg       0.86      0.87      0.85      2000

In [100]:
rf = RandomForestClassifier(n_estimators=100,random_state=42,max_depth=20)
rf.fit(X_train, y_train)
pred_rf = rf.predict(X_test)
print(accuracy_score(y_test, pred_rf))

0.864

In [101]:
print(classification_report(y_test, pred_rf))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92      1607
           1       0.76      0.45      0.56       393

    accuracy                           0.86      2000
   macro avg       0.82      0.71      0.74      2000
weighted avg       0.85      0.86      0.85      2000

In [102]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
pred_knn = knn.predict(X_test)
print(accuracy_score(y_test, pred_knn))
print(classification_report(y_test, pred_knn))

0.767
              precision    recall  f1-score   support

           0       0.81      0.93      0.87      1607
           1       0.24      0.08      0.12       393

    accuracy                           0.77      2000
   macro avg       0.52      0.51      0.49      2000
weighted avg       0.69      0.77      0.72      2000

In [103]:
rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    max_depth=10
)

rf.fit(X_train, y_train)

pred_rf = rf.predict(X_test)

print("Training Accuracy:", rf.score(X_train, y_train))
print("Testing Accuracy:", accuracy_score(y_test, pred_rf))

print(classification_report(y_test, pred_rf))

Training Accuracy: 0.898125
Testing Accuracy: 0.8665
              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1607
           1       0.80      0.43      0.56       393

    accuracy                           0.87      2000
   macro avg       0.84      0.70      0.74      2000
weighted avg       0.86      0.87      0.85      2000

In [104]:
rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    max_depth=15,
    min_samples_leaf=3
)

rf.fit(X_train, y_train)

pred_rf = rf.predict(X_test)

print("Training Accuracy:", rf.score(X_train, y_train))
print("Testing Accuracy:", accuracy_score(y_test, pred_rf))

print(classification_report(y_test, pred_rf))

Training Accuracy: 0.926125
Testing Accuracy: 0.866
              precision    recall  f1-score   support

           0       0.88      0.97      0.92      1607
           1       0.78      0.45      0.57       393

    accuracy                           0.87      2000
   macro avg       0.83      0.71      0.74      2000
weighted avg       0.86      0.87      0.85      2000

In [105]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier()

gb.fit(X_train, y_train)

pred_gb = gb.predict(X_test)

print("Training Accuracy:", gb.score(X_train, y_train))
print("Testing Accuracy:", accuracy_score(y_test, pred_gb))

print(classification_report(y_test, pred_gb))

Training Accuracy: 0.8715
Testing Accuracy: 0.868
              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1607
           1       0.77      0.47      0.58       393

    accuracy                           0.87      2000
   macro avg       0.82      0.72      0.75      2000
weighted avg       0.86      0.87      0.86      2000

In [106]:
gb = GradientBoostingClassifier(
    n_estimators=200
)

gb.fit(X_train, y_train)

pred_gb = gb.predict(X_test)

print("Training Accuracy:", gb.score(X_train, y_train))
print("Testing Accuracy:", accuracy_score(y_test, pred_gb))

print(classification_report(y_test, pred_gb))

Training Accuracy: 0.8835
Testing Accuracy: 0.872
              precision    recall  f1-score   support

           0       0.89      0.96      0.92      1607
           1       0.77      0.50      0.61       393

    accuracy                           0.87      2000
   macro avg       0.83      0.73      0.76      2000
weighted avg       0.86      0.87      0.86      2000

In [107]:
from xgboost import XGBClassifier

In [108]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.30.7)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [109]:
xgb = XGBClassifier()

xgb.fit(X_train, y_train)

pred_xgb = xgb.predict(X_test)

print("Training Accuracy:", xgb.score(X_train, y_train))
print("Testing Accuracy:", accuracy_score(y_test, pred_xgb))

print(classification_report(y_test, pred_xgb))

Training Accuracy: 0.96675
Testing Accuracy: 0.86
              precision    recall  f1-score   support

           0       0.89      0.95      0.92      1607
           1       0.70      0.50      0.58       393

    accuracy                           0.86      2000
   macro avg       0.79      0.72      0.75      2000
weighted avg       0.85      0.86      0.85      2000

In [110]:
xgb = XGBClassifier(
    max_depth=3,
)

xgb.fit(X_train, y_train)

pred_xgb = xgb.predict(X_test)

print("Training Accuracy:", xgb.score(X_train, y_train))
print("Testing Accuracy:", accuracy_score(y_test, pred_xgb))

print(classification_report(y_test, pred_xgb))

Training Accuracy: 0.886
Testing Accuracy: 0.8705
              precision    recall  f1-score   support

           0       0.89      0.96      0.92      1607
           1       0.76      0.49      0.60       393

    accuracy                           0.87      2000
   macro avg       0.82      0.73      0.76      2000
weighted avg       0.86      0.87      0.86      2000

In [111]:
from xgboost import XGBClassifier

# Create final model
final_model = XGBClassifier(
    max_depth=3
)

# Train model
final_model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [114]:
final_model.save_model("churn_model.json")

print("Model saved successfully!")

Model saved successfully!

In [115]:
from google.colab import files

files.download("churn_model.json")

In [112]:
from google.colab import files

files.download("churn_model.pkl")

In [113]:
df.columns

Index(['CustomerId', 'CreditScore', 'Geography', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited', 'BalanceSalaryRatio', 'AgeActive'],
      dtype='object')