In [1]:
# Install required NLP libraries

!pip install contractions nltk pandas

Collecting contractions
  Downloading contractions-0.1.73-py2.py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting textsearch>=0.0.21 (from contractions)
  Downloading textsearch-0.0.24-py2.py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting anyascii (from textsearch>=0.0.21->contractions)
  Downloading anyascii-0.3.3-py3-none-any.whl.metadata (1.6 kB)
Collecting pyahocorasick (from textsearch>=0.0.21->contractions)
  Downloading pyahocorasick-2.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (13 kB)
Downloading contractions-0.1.73-py2.py3-none-any.whl (8.7 kB)
Downloading textsearch-0.0.24-py2.py3-none-any.whl (7.6 kB)
Downloading anyascii-0.3.3-py3-none-any.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.1/345.1 kB 30.0 MB/s eta 0:00:00
Downloading pyahocorasick-2.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 13.0 MB/s eta 0:00:00
Installing collected packages: pyahocorasick, anyascii, textsearch, contractions
Successfully installed anyascii-0.3.3 contractions-0.1.73 pyahocorasick-2.3.1 textsearch-0.0.24

In [2]:
import re
import nltk
import contractions
import pandas as pd

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Download required NLTK resources
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

print("Libraries imported successfully!")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

Libraries imported successfully!

In [3]:
# Get English stopwords
stop_words = set(stopwords.words('english'))

def clean_text(text):
    # 1. Convert text to lowercase
    text = text.lower()

    # 2. Expand contractions
    text = contractions.fix(text)

    # 3. Remove hashtags and mentions
    text = re.sub(r'[@#]\w+', '', text)

    # 4. Remove special characters and punctuation
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # 5. Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    # 6. Tokenize the text
    words = word_tokenize(text)

    # 7. Remove stopwords
    words = [word for word in words if word not in stop_words]

    # 8. Join words back into a sentence
    cleaned_text = ' '.join(words)

    return cleaned_text

In [4]:
review = """I'm really HAPPY about this product!!! It's amazing & I don't
think I've ever used something this good. @product #awesome"""

print("Original Review:")
print(review)

Original Review:
I'm really HAPPY about this product!!! It's amazing & I don't
think I've ever used something this good. @product #awesome

In [5]:
cleaned_review = clean_text(review)

print("Cleaned Review:")
print(cleaned_review)

Cleaned Review:
really happy product amazing think ever used something good

In [6]:
comparison = pd.DataFrame({
    "Original Text": [review],
    "Cleaned Text": [cleaned_review]
})

comparison

,Original Text,Cleaned Text
0,I'm really HAPPY about this product!!! It's am...,really happy product amazing think ever used s...

In [7]:
# Count words before preprocessing
words_before = len(word_tokenize(review))

# Count words after preprocessing
words_after = len(word_tokenize(cleaned_review))

print("Number of words before preprocessing:", words_before)
print("Number of words after preprocessing:", words_after)

Number of words before preprocessing: 30
Number of words after preprocessing: 9

In [8]:
task1_result = pd.DataFrame({
    "Original Text": [review],
    "Cleaned Text": [cleaned_review],
    "Words Before": [words_before],
    "Words After": [words_after]
})

task1_result

,Original Text,Cleaned Text,Words Before,Words After
0,I'm really HAPPY about this product!!! It's am...,really happy product amazing think ever used s...,30,9

In [9]:
reduction = words_before - words_after
reduction_percentage = (reduction / words_before) * 100

print("Words before preprocessing :", words_before)
print("Words after preprocessing  :", words_after)
print("Words removed              :", reduction)
print("Reduction percentage       :", round(reduction_percentage, 2), "%")

Words before preprocessing : 30
Words after preprocessing  : 9
Words removed              : 21
Reduction percentage       : 70.0 %

In [10]:
# Task 2: Social Media Text Cleaning

social_comments = [
    "OMG!!! I can't believe this 😍 @user #Amazing",
    "This movie wasn't good... I don't recommend it!!!",
    "I'm LOVING this product!!! It's sooo good 😍"
]

print("Number of comments:", len(social_comments))

for i, comment in enumerate(social_comments, start=1):
    print(f"\nComment {i}:")
    print(comment)

Number of comments: 3

Comment 1:
OMG!!! I can't believe this 😍 @user #Amazing

Comment 2:
This movie wasn't good... I don't recommend it!!!

Comment 3:
I'm LOVING this product!!! It's sooo good 😍

In [11]:
# Clean all social media comments

cleaned_comments = []

for comment in social_comments:
    cleaned = clean_text(comment)
    cleaned_comments.append(cleaned)

for i, cleaned in enumerate(cleaned_comments, start=1):
    print(f"\nCleaned Comment {i}:")
    print(cleaned)

Cleaned Comment 1:
omg believe

Cleaned Comment 2:
movie good recommend

Cleaned Comment 3:
loving product sooo good

In [12]:
# Compare original and cleaned comments

task2_comparison = pd.DataFrame({
    "Original Comment": social_comments,
    "Cleaned Comment": cleaned_comments
})

task2_comparison

                                    Original Comment           Cleaned Comment
0       OMG!!! I can't believe this 😍 @user #Amazing               omg believe
1  This movie wasn't good... I don't recommend it!!!      movie good recommend
2        I'm LOVING this product!!! It's sooo good 😍  loving product sooo good

In [13]:
# Calculate word counts before and after cleaning

words_before_task2 = []
words_after_task2 = []

for original, cleaned in zip(social_comments, cleaned_comments):
    before = len(word_tokenize(original))
    after = len(word_tokenize(cleaned))

    words_before_task2.append(before)
    words_after_task2.append(after)

task2_comparison["Words Before"] = words_before_task2
task2_comparison["Words After"] = words_after_task2

task2_comparison

,Original Comment,Cleaned Comment,Words Before,Words After
0,OMG!!! I can't believe this 😍 @user #Amazing,omg believe,14,2
1,This movie wasn't good... I don't recommend it!!!,movie good recommend,14,3
2,I'm LOVING this product!!! It's sooo good 😍,loving product sooo good,13,4

In [14]:
# Overall word reduction

total_before_task2 = sum(words_before_task2)
total_after_task2 = sum(words_after_task2)

total_removed_task2 = total_before_task2 - total_after_task2

reduction_percentage_task2 = (
    total_removed_task2 / total_before_task2
) * 100

print("Total words before cleaning :", total_before_task2)
print("Total words after cleaning  :", total_after_task2)
print("Total words removed         :", total_removed_task2)
print(
    "Reduction percentage        :",
    round(reduction_percentage_task2, 2),
    "%"
)

Total words before cleaning : 41
Total words after cleaning  : 9
Total words removed         : 32
Reduction percentage        : 78.05 %

In [15]:
# Task 3: Create 100 customer reviews

reviews = [
    "I absolutely love this product! It's amazing and works perfectly.",
    "The product is really good and I am very happy with my purchase.",
    "I don't like this product because it stopped working after a week.",
    "Excellent quality and fast delivery. I highly recommend it!",
    "The service was great and the staff were very helpful.",
    "This product is terrible and I am extremely disappointed.",
    "I am happy with the quality and the price is reasonable.",
    "The delivery was late but the product itself is good.",
    "Amazing product! I will definitely buy it again.",
    "The quality is poor and the product feels cheap.",

    "I really enjoyed using this product. It is easy to use.",
    "The product wasn't what I expected but it is okay.",
    "Fantastic quality and excellent customer service.",
    "I can't recommend this product because it broke quickly.",
    "The product works well and looks very stylish.",
    "I am not satisfied with the product or the service.",
    "Great value for money and very good quality.",
    "The packaging was excellent and the product arrived safely.",
    "I love this product and would definitely recommend it.",
    "The product is not worth the money.",

    "The customer service was excellent and very friendly.",
    "I am very disappointed with this purchase.",
    "This is one of the best products I have ever purchased.",
    "The product arrived damaged and I had to return it.",
    "Really good product with excellent performance.",
    "I don't think this product is worth the price.",
    "The delivery was quick and the packaging was good.",
    "I am extremely happy with my purchase.",
    "The product stopped working and customer support was not helpful.",
    "Excellent product and amazing quality.",

    "I really like the design and performance of this product.",
    "The product is okay but could be better.",
    "Very poor quality and disappointing service.",
    "I would definitely buy this product again.",
    "The product is easy to use and works perfectly.",
    "I wasn't happy with the delivery time.",
    "Amazing service and very helpful staff.",
    "This product is expensive but the quality is excellent.",
    "I can't believe how good this product is.",
    "The product did not work as expected.",

    "I am satisfied with the product and the delivery was fast.",
    "This is a fantastic product with great features.",
    "The quality was poor and I am not happy.",
    "I highly recommend this product to everyone.",
    "The customer service team was very helpful.",
    "The product arrived on time and works well.",
    "I don't like the design of this product.",
    "Excellent purchase and very good value.",
    "The product is amazing and exceeded my expectations.",
    "I was disappointed because the product was damaged.",

    "Really excellent quality and very fast delivery.",
    "The product works perfectly and I love it.",
    "I am not satisfied with the quality.",
    "This product is very useful and easy to use.",
    "The service was terrible and the staff were rude.",
    "I would recommend this product to my friends.",
    "The price is good but the quality could be better.",
    "I am very happy with the product.",
    "The delivery was extremely slow.",
    "Amazing quality and excellent performance.",

    "I love the features of this product.",
    "The product is not good and stopped working.",
    "Very happy with my purchase and the service.",
    "I don't recommend this product to anyone.",
    "The packaging was great and delivery was fast.",
    "This product is excellent and very reliable.",
    "I was not happy with the customer service.",
    "The product is worth the money.",
    "The quality is amazing and the design is beautiful.",
    "The product arrived late but works well.",

    "I really enjoyed this product and would buy it again.",
    "The quality is not good for the price.",
    "Excellent customer service and quick response.",
    "I am extremely disappointed with this product.",
    "This product works very well and is easy to use.",
    "I highly recommend this excellent product.",
    "The product was damaged when it arrived.",
    "I am happy with the performance.",
    "The service was good but the delivery was slow.",
    "This is an amazing product with excellent quality.",

    "I don't think I will buy this product again.",
    "The product is fantastic and works perfectly.",
    "Very good quality and reasonable price.",
    "The customer service was not helpful.",
    "I love this product because it is reliable.",
    "The product is disappointing and expensive.",
    "Fast delivery and excellent packaging.",
    "I am very satisfied with my purchase.",
    "The product could be improved but is still useful.",
    "I would definitely recommend this product.",

    "Excellent quality and fantastic performance.",
    "The product did not meet my expectations.",
    "I am happy with the purchase and the service.",
    "The product is very easy to use.",
    "I don't recommend this product because of poor quality.",
    "Amazing product and excellent customer support.",
    "The delivery was fast and the product was perfect.",
    "I am disappointed with the quality.",
    "Great product and very good customer service.",
    "I will definitely purchase this product again."
]

print("Number of reviews:", len(reviews))

Number of reviews: 100

In [16]:
# Create DataFrame

df_reviews = pd.DataFrame({
    "review": reviews
})

print("Dataset shape:", df_reviews.shape)

df_reviews.head(10)

Dataset shape: (100, 1)

                                              review
0  I absolutely love this product! It's amazing a...
1  The product is really good and I am very happy...
2  I don't like this product because it stopped w...
3  Excellent quality and fast delivery. I highly ...
4  The service was great and the staff were very ...
5  This product is terrible and I am extremely di...
6  I am happy with the quality and the price is r...
7  The delivery was late but the product itself i...
8   Amazing product! I will definitely buy it again.
9   The quality is poor and the product feels cheap.

In [17]:
# Count words before preprocessing

df_reviews["words_before"] = df_reviews["review"].apply(
    lambda x: len(word_tokenize(x))
)

df_reviews[["review", "words_before"]].head(10)

                                              review  words_before
0  I absolutely love this product! It's amazing a...            13
1  The product is really good and I am very happy...            14
2  I don't like this product because it stopped w...            14
3  Excellent quality and fast delivery. I highly ...            11
4  The service was great and the staff were very ...            11
5  This product is terrible and I am extremely di...            10
6  I am happy with the quality and the price is r...            12
7  The delivery was late but the product itself i...            11
8   Amazing product! I will definitely buy it again.            10
9   The quality is poor and the product feels cheap.            10

In [18]:
# Apply text cleaning pipeline

df_reviews["cleaned_review"] = df_reviews["review"].apply(clean_text)

df_reviews[["review", "cleaned_review"]].head(10)

,review,cleaned_review
0,I absolutely love this product! It's amazing a...,absolutely love product amazing works perfectly
1,The product is really good and I am very happy...,product really good happy purchase
2,I don't like this product because it stopped w...,like product stopped working week
3,Excellent quality and fast delivery. I highly ...,excellent quality fast delivery highly recommend
4,The service was great and the staff were very ...,service great staff helpful
5,This product is terrible and I am extremely di...,product terrible extremely disappointed
6,I am happy with the quality and the price is r...,happy quality price reasonable
7,The delivery was late but the product itself i...,delivery late product good
8,Amazing product! I will definitely buy it again.,amazing product definitely buy
9,The quality is poor and the product feels cheap.,quality poor product feels cheap

In [19]:
# Count words after preprocessing

df_reviews["words_after"] = df_reviews["cleaned_review"].apply(
    lambda x: len(word_tokenize(x))
)

df_reviews[
    ["review", "cleaned_review", "words_before", "words_after"]
].head(10)

,review,cleaned_review,words_before,words_after
0,I absolutely love this product! It's amazing a...,absolutely love product amazing works perfectly,13,6
1,The product is really good and I am very happy...,product really good happy purchase,14,5
2,I don't like this product because it stopped w...,like product stopped working week,14,5
3,Excellent quality and fast delivery. I highly ...,excellent quality fast delivery highly recommend,11,6
4,The service was great and the staff were very ...,service great staff helpful,11,4
5,This product is terrible and I am extremely di...,product terrible extremely disappointed,10,4
6,I am happy with the quality and the price is r...,happy quality price reasonable,12,4
7,The delivery was late but the product itself i...,delivery late product good,11,4
8,Amazing product! I will definitely buy it again.,amazing product definitely buy,10,4
9,The quality is poor and the product feels cheap.,quality poor product feels cheap,10,5

In [20]:
# Calculate average word counts

average_words_before = df_reviews["words_before"].mean()
average_words_after = df_reviews["words_after"].mean()

print(
    "Average number of words before cleaning:",
    round(average_words_before, 2)
)

print(
    "Average number of words after cleaning:",
    round(average_words_after, 2)
)

Average number of words before cleaning: 9.1
Average number of words after cleaning: 3.9

In [21]:
# Calculate reduction in average word count

average_reduction = (
    average_words_before - average_words_after
)

reduction_percentage = (
    average_reduction / average_words_before
) * 100

print("Average words before:", round(average_words_before, 2))
print("Average words after :", round(average_words_after, 2))
print("Average words removed:", round(average_reduction, 2))
print(
    "Reduction percentage:",
    round(reduction_percentage, 2),
    "%"
)

Average words before: 9.1
Average words after : 3.9
Average words removed: 5.2
Reduction percentage: 57.14 %

In [22]:
from collections import Counter

# Combine all cleaned reviews
all_cleaned_words = []

for review in df_reviews["cleaned_review"]:
    words = word_tokenize(review)
    all_cleaned_words.extend(words)

# Count word frequencies
word_counts = Counter(all_cleaned_words)

# Get 10 most frequent words
top_10_words = word_counts.most_common(10)

print("Top 10 most frequent words:\n")

for rank, (word, count) in enumerate(top_10_words, start=1):
    print(f"{rank}. {word} - {count}")

Top 10 most frequent words:

1. product - 63
2. quality - 20
3. excellent - 17
4. service - 15
5. good - 13
6. delivery - 11
7. happy - 10
8. amazing - 9
9. recommend - 9
10. customer - 9

In [23]:
# Create Top 10 words DataFrame

top_10_df = pd.DataFrame(
    top_10_words,
    columns=["Word", "Frequency"]
)

top_10_df.index = range(1, len(top_10_df) + 1)
top_10_df.index.name = "Rank"

top_10_df

           Word  Frequency
Rank
1       product         63
2       quality         20
3     excellent         17
4       service         15
5          good         13
6      delivery         11
7         happy         10
8       amazing          9
9     recommend          9
10     customer          9

In [24]:
# Display complete processed dataset

df_reviews

,review,words_before,cleaned_review,words_after
0,I absolutely love this product! It's amazing a...,13,absolutely love product amazing works perfectly,6
1,The product is really good and I am very happy...,14,product really good happy purchase,5
2,I don't like this product because it stopped w...,14,like product stopped working week,5
3,Excellent quality and fast delivery. I highly ...,11,excellent quality fast delivery highly recommend,6
4,The service was great and the staff were very ...,11,service great staff helpful,4
...,...,...,...,...
95,Amazing product and excellent customer support.,7,amazing product excellent customer support,5
96,The delivery was fast and the product was perf...,10,delivery fast product perfect,4
97,I am disappointed with the quality.,7,disappointed quality,2
98,Great product and very good customer service.,8,great product good customer service,5
99,I will definitely purchase this product again.,8,definitely purchase product,3

In [25]:
# Task 3 Final Summary

print("=" * 50)
print("TASK 3 - CUSTOMER REVIEW PREPROCESSING")
print("=" * 50)

print("Total number of reviews:", len(df_reviews))
print(
    "Average words before cleaning:",
    round(average_words_before, 2)
)
print(
    "Average words after cleaning:",
    round(average_words_after, 2)
)
print(
    "Average words removed:",
    round(average_reduction, 2)
)
print(
    "Text reduction percentage:",
    round(reduction_percentage, 2),
    "%"
)

print("\nTop 10 Most Frequent Words:")
print(top_10_df)

==================================================
TASK 3 - CUSTOMER REVIEW PREPROCESSING
==================================================
Total number of reviews: 100
Average words before cleaning: 9.1
Average words after cleaning: 3.9
Average words removed: 5.2
Text reduction percentage: 57.14 %

Top 10 Most Frequent Words:
           Word  Frequency
Rank
1       product         63
2       quality         20
3     excellent         17
4       service         15
5          good         13
6      delivery         11
7         happy         10
8       amazing          9
9     recommend          9
10     customer          9

In [26]:
# Task 4: Create 20 news articles

news_articles = [
    """The government announced a new education policy today. The policy will improve schools
    and provide better opportunities for students across the country.""",

    """The technology company launched a new smartphone with advanced features. The device
    has a powerful processor, improved camera, and longer battery life.""",

    """Heavy rainfall caused flooding in several parts of the city. Emergency teams were sent
    to affected areas and residents were asked to remain indoors.""",

    """The national football team won an important match yesterday. The players performed
    extremely well and scored three goals during the game.""",

    """A new healthcare program was announced by the government. The program will provide
    affordable medical services to people in rural areas.""",

    """Scientists have discovered a new method that could help reduce pollution. The research
    team believes the technology can be used in many industries.""",

    """The stock market increased significantly on Monday. Investors were optimistic about
    economic growth and several major companies reported strong results.""",

    """A new train service will connect several major cities. Officials said the service will
    reduce travel time and provide better transportation facilities.""",

    """The university announced new scholarships for students. The scholarships will support
    talented students who need financial assistance for their education.""",

    """The city opened a new public park this weekend. The park includes walking paths,
    children's play areas, gardens, and sports facilities.""",

    """The international conference brought together experts from different countries.
    Researchers discussed climate change, technology, healthcare, and economic development.""",

    """The company reported strong sales during the last quarter. Its revenue increased because
    customers showed greater interest in its new products.""",

    """A new environmental project aims to protect forests and wildlife. Volunteers will work
    with local communities to plant trees and protect natural habitats.""",

    """The education department announced changes to school examinations. The new system will
    focus more on practical knowledge and problem solving skills.""",

    """The weather department predicted heavy rainfall for the next few days. People living
    near rivers were advised to take necessary safety precautions.""",

    """Researchers developed a new artificial intelligence system. The system can analyze
    large amounts of data and help doctors identify diseases more quickly.""",

    """The government plans to build new roads and bridges across the region. Officials said
    the infrastructure project will improve transportation and create new jobs.""",

    """The basketball team reached the final after defeating its opponents in a close match.
    Fans celebrated the team's impressive performance.""",

    """A popular company announced that it will launch a new electric vehicle. The vehicle
    will have improved battery technology and several modern safety features.""",

    """The annual business conference ended successfully on Friday. Business leaders discussed
    investment, innovation, technology, and opportunities for future economic growth."""
]

print("Number of news articles:", len(news_articles))

Number of news articles: 20

In [27]:
# Create DataFrame

df_news = pd.DataFrame({
    "article": news_articles
})

print("Dataset shape:", df_news.shape)

df_news.head()

Dataset shape: (20, 1)

                                             article
0  The government announced a new education polic...
1  The technology company launched a new smartpho...
2  Heavy rainfall caused flooding in several part...
3  The national football team won an important ma...
4  A new healthcare program was announced by the ...

In [28]:
# Count words before preprocessing

df_news["words_before"] = df_news["article"].apply(
    lambda x: len(word_tokenize(x))
)

df_news[["article", "words_before"]].head()

                                             article  words_before
0  The government announced a new education polic...            24
1  The technology company launched a new smartpho...            26
2  Heavy rainfall caused flooding in several part...            26
3  The national football team won an important ma...            23
4  A new healthcare program was announced by the ...            23

In [29]:
# Clean all news articles

df_news["cleaned_article"] = df_news["article"].apply(clean_text)

df_news[["article", "cleaned_article"]].head()

,article,cleaned_article
0,The government announced a new education polic...,government announced new education policy toda...
1,The technology company launched a new smartpho...,technology company launched new smartphone adv...
2,Heavy rainfall caused flooding in several part...,heavy rainfall caused flooding several parts c...
3,The national football team won an important ma...,national football team important match yesterd...
4,A new healthcare program was announced by the ...,new healthcare program announced government pr...

In [30]:
# Count words after preprocessing

df_news["words_after"] = df_news["cleaned_article"].apply(
    lambda x: len(word_tokenize(x))
)

df_news[
    ["article", "cleaned_article", "words_before", "words_after"]
].head()

,article,cleaned_article,words_before,words_after
0,The government announced a new education polic...,government announced new education policy toda...,24,15
1,The technology company launched a new smartpho...,technology company launched new smartphone adv...,26,15
2,Heavy rainfall caused flooding in several part...,heavy rainfall caused flooding several parts c...,26,16
3,The national football team won an important ma...,national football team important match yesterd...,23,14
4,A new healthcare program was announced by the ...,new healthcare program announced government pr...,23,13

In [31]:
# Total word counts

total_words_before = df_news["words_before"].sum()
total_words_after = df_news["words_after"].sum()

print("Total words before preprocessing:", total_words_before)
print("Total words after preprocessing :", total_words_after)

Total words before preprocessing: 484
Total words after preprocessing : 301

In [32]:
from collections import Counter

# Combine all cleaned news articles

all_news_words = []

for article in df_news["cleaned_article"]:
    words = word_tokenize(article)
    all_news_words.extend(words)

# Count word frequencies

news_word_counts = Counter(all_news_words)

# Top 10 words

top_10_news_words = news_word_counts.most_common(10)

print("Top 10 most frequent words:\n")

for rank, (word, count) in enumerate(top_10_news_words, start=1):
    print(f"{rank}. {word} - {count}")

Top 10 most frequent words:

1. new - 14
2. announced - 5
3. technology - 5
4. several - 4
5. team - 4
6. government - 3
7. education - 3
8. provide - 3
9. students - 3
10. company - 3

In [33]:
# Top 10 words DataFrame

top_10_news_df = pd.DataFrame(
    top_10_news_words,
    columns=["Word", "Frequency"]
)

top_10_news_df.index = range(1, 11)
top_10_news_df.index.name = "Rank"

top_10_news_df

            Word  Frequency
Rank
1            new         14
2      announced          5
3     technology          5
4        several          4
5           team          4
6     government          3
7      education          3
8        provide          3
9       students          3
10       company          3

In [34]:
# Find the most frequent stopwords in original articles

all_original_words = []

for article in df_news["article"]:
    words = word_tokenize(article.lower())
    all_original_words.extend(words)

# Keep only stopwords

stopword_counts = Counter(
    word for word in all_original_words
    if word in stop_words
)

top_stopwords = stopword_counts.most_common(10)

print("Most frequent stopwords:\n")

for rank, (word, count) in enumerate(top_stopwords, start=1):
    print(f"{rank}. {word} - {count}")

Most frequent stopwords:

1. the - 35
2. and - 16
3. a - 12
4. will - 10
5. to - 8
6. for - 5
7. in - 5
8. were - 4
9. on - 3
10. its - 3

In [35]:
# Stopword frequency table

top_stopwords_df = pd.DataFrame(
    top_stopwords,
    columns=["Stopword", "Frequency"]
)

top_stopwords_df.index = range(1, len(top_stopwords_df) + 1)
top_stopwords_df.index.name = "Rank"

top_stopwords_df

     Stopword  Frequency
Rank
1         the         35
2         and         16
3           a         12
4        will         10
5          to          8
6         for          5
7          in          5
8        were          4
9          on          3
10        its          3

In [36]:
# Calculate text reduction

words_removed = total_words_before - total_words_after

text_reduction_percentage = (
    words_removed / total_words_before
) * 100

print("Total words before preprocessing :", total_words_before)
print("Total words after preprocessing  :", total_words_after)
print("Total words removed              :", words_removed)
print(
    "Text size reduction              :",
    round(text_reduction_percentage, 2),
    "%"
)

Total words before preprocessing : 484
Total words after preprocessing  : 301
Total words removed              : 183
Text size reduction              : 37.81 %

In [37]:
# Average words per article

average_before_news = df_news["words_before"].mean()
average_after_news = df_news["words_after"].mean()

print(
    "Average words per article before cleaning:",
    round(average_before_news, 2)
)

print(
    "Average words per article after cleaning :",
    round(average_after_news, 2)
)

Average words per article before cleaning: 24.2
Average words per article after cleaning : 15.05

In [38]:
# Before and after comparison

news_comparison = df_news[
    ["article", "cleaned_article", "words_before", "words_after"]
]

news_comparison

,article,cleaned_article,words_before,words_after
0,The government announced a new education polic...,government announced new education policy toda...,24,15
1,The technology company launched a new smartpho...,technology company launched new smartphone adv...,26,15
2,Heavy rainfall caused flooding in several part...,heavy rainfall caused flooding several parts c...,26,16
3,The national football team won an important ma...,national football team important match yesterd...,23,14
4,A new healthcare program was announced by the ...,new healthcare program announced government pr...,23,13
5,Scientists have discovered a new method that c...,scientists discovered new method could help re...,25,15
6,The stock market increased significantly on Mo...,stock market increased significantly monday in...,22,15
7,A new train service will connect several major...,new train service connect several major cities...,24,17
8,The university announced new scholarships for ...,university announced new scholarships students...,22,13
9,The city opened a new public park this weekend...,city opened new public park weekend park inclu...,27,16
10,The international conference brought together ...,international conference brought together expe...,23,15
11,The company reported strong sales during the l...,company reported strong sales last quarter rev...,23,14
12,A new environmental project aims to protect fo...,new environmental project aims protect forests...,25,16
13,The education department announced changes to ...,education department announced changes school ...,23,14
14,The weather department predicted heavy rainfal...,weather department predicted heavy rainfall ne...,24,16
15,Researchers developed a new artificial intelli...,researchers developed new artificial intellige...,24,16
16,The government plans to build new roads and br...,government plans build new roads bridges acros...,26,17
17,The basketball team reached the final after de...,basketball team reached final defeating oppone...,23,13
18,A popular company announced that it will launc...,popular company announced launch new electric ...,26,15
19,The annual business conference ended successfu...,annual business conference ended successfully ...,25,16

In [39]:
# Task 4 Final Summary

print("=" * 60)
print("TASK 4 - NEWS ARTICLE TEXT CLEANING")
print("=" * 60)

print("\nNumber of articles:", len(df_news))

print(
    "\n1. Total words before preprocessing:",
    total_words_before
)

print(
    "2. Total words after preprocessing :",
    total_words_after
)

print(
    "3. Total words removed:",
    words_removed
)

print(
    "4. Text size reduction:",
    round(text_reduction_percentage, 2),
    "%"
)

print(
    "\n5. Top 10 most frequent words:"
)

print(top_10_news_df)

print(
    "\n6. Most frequent stopwords:"
)

print(top_stopwords_df)

============================================================
TASK 4 - NEWS ARTICLE TEXT CLEANING
============================================================

Number of articles: 20

1. Total words before preprocessing: 484
2. Total words after preprocessing : 301
3. Total words removed: 183
4. Text size reduction: 37.81 %

5. Top 10 most frequent words:
            Word  Frequency
Rank
1            new         14
2      announced          5
3     technology          5
4        several          4
5           team          4
6     government          3
7      education          3
8        provide          3
9       students          3
10       company          3

6. Most frequent stopwords:
     Stopword  Frequency
Rank
1         the         35
2         and         16
3           a         12
4        will         10
5          to          8
6         for          5
7          in          5
8        were          4
9          on          3
10        its          3